const cards = [
  {
    id: 1,
    mediaImg: './images/Facebook-color.svg',
    color: 'linear-gradient(180deg, #39579a 0%, #2c4479 97.23%), #39579a',
    followers: '1,701',
    text: 'followers',
    followersChange: '+4',
    userImg: './images/user-pic.svg',
    media: 'Facebook',
    user: '@abhisek.daas',
  },
  {
    id: 2,
    mediaImg: './images/Twitter-color.svg',
    color: 'linear-gradient(180deg, #059FF5 0%, #059FC3 100%), #059FF5',
    followers: '1,567',
    text: 'followers',
    followersChange: '-3',
    userImg: './images/user-pic-2.svg',
    media: 'Twitter',
    user: '@wholetthedasout',
  },
  {
    id: 3,
    mediaImg: './images/Instagram-color.svg',
    color: 'linear-gradient(to right top, #fac06b, #ffa860, #ff8e5d, #ff7262, #ff556d, #f84478, #ed3585, #df2a92, #d02d9c, #be32a6, #aa38ae, #943eb4)',
    followers: '1,139',
    text: 'followers',
    followersChange: '+11',
    userImg: './images/user-pic-3.svg',
    media: 'Instagram',
    user: '@wholetthedasout',
  },
  {
    id: 4,
    mediaImg: './images/LinkedIn-color.svg',
    color: 'linear-gradient(180deg, #007EBB 0%, #007E9D 98.51%), #007EBB',
    followers: '2,106',
    text: 'followers',
    followersChange: '+39',
    userImg: './images/user-pic.svg',
    media: 'LinkedIn',
    user: '@abhisekd3',
  },
  {
    id: 5,
    mediaImg: './images/Youtube-color.svg',
    color: 'linear-gradient(180deg, #CE1312 0%, #B01312 100%), #CE1312',
    followers: '3,190',
    text: 'Subscribers',
    followersChange: '+22',
    userImg: './images/user-pic-4.svg',
    media: 'YouTube',
    user: '@TheAbhisekD',
  },
  {
    id: 6,
    mediaImg: './images/Snapchat.svg',
    color: 'linear-gradient(180deg, #FFFE00 0%, #F3F200 96.43%), #FFFE00',
    textColor: 'black',
    followers: '8,754',
    text: 'snap score',
    followersChange: '',
    userImg: './images/user-pic-3.svg',
    media: 'Snapchat',
    user: '@abhisekd',
  },
  {
    id: 7,
    mediaImg: './images/GooglePlus-color.svg',
    color: 'linear-gradient(180deg, #F93F2D 0%, #C73F2D 100%), #F93F2D',
    followers: '1,033',
    text: 'followers',
    followersChange: '',
    userImg: './images/user-pic-3.svg',
    media: 'Google+',
    user: '@+AbhisekDas',
  },
  {
    id: 8,
    mediaImg: './images/Vine-color.svg',
    color: 'linear-gradient(180deg, #00B687 0%, #008E87 100%), #00B687',
    followers: '1,045',
    text: 'loops',
    followersChange: '',
    userImg: './images/user-pic-5.svg',
    media: 'Vine',
    user: '@1316139228245221376',
  },
];
export default cards;
